# Job finished at: 2026-03-12 10:11:05
# Job started at: 2026-03-12 10:02:48
# Job finished at: 2026-03-12 00:49:52
# Job started at: 2026-03-12 00:41:39
base = ["../config_priors.toml", "../config_paths.toml", "../config.toml"]

[inference]
model = "SNModel"
num_warmup = 500
num_samples = 500
num_chains = 1
seed = 44

[pv_model]
kind = "precomputed_los_Carrick2015"
galaxy_bias = "spline"
spline_bias_knots_delta = [-0.5, 0.0, 0.5, 1.0, 2.0, 3.0, 5.0]
density_dependent_sigma_v = true
which_Vext = "constant"
r_limits_malmquist = "auto"
dr_malmquist = 0.5
los_decay_scale = 10.0

[model.priors.spline_bias_y]
dist = "normal"
loc = 0.0
scale = 3.0

[model.priors.sigma_int]
dist = "jeffreys"
low = 0.005
high = 1.0

[model.priors.sigma_v_low]
dist = "maxwell"
scale = 200

[model.priors.sigma_v_high]
dist = "maxwell"
scale = 200

[model.priors.log_sigma_v_rho_t]
dist = "normal"
loc = 1.0
scale = 5.0

[model.priors.sigma_v_k]
dist = "truncated_normal"
low = 0.0
mean = 1.0
scale = 1.0

[io]
catalogue_name = "Foundation"
fname_output = "results/test_density_sigma_v.hdf5"

[io.Foundation]
root = "data/Foundation"
zcmb_min = "none"
zcmb_max = 0.05
b_min = 7.5
nsamples_subsample = "none"
seed_subsample = 42
los_file = "data/Foundation/los_Foundation_<X>.hdf5"
