#!/usr/bin/env python
"""
Prepare reconstruction-derived LOS files and H0 field caches from one command.

This is an orchestration layer around the production preprocessing code: LOS
files use the standard HDF5 schema and cache files are generated by the same
config loaders used by inference.
"""
import argparse
import os
import sys
import tempfile
from pathlib import Path
from textwrap import dedent

# This is a preprocessing script; set before importing candel/JAX.
os.environ.setdefault("JAX_PLATFORMS", "cpu")
_USER = os.environ.get("USER") or "user"
os.environ.setdefault(
    "MPLCONFIGDIR", os.path.join(tempfile.gettempdir(),
                                 f"candel_mpl_{_USER}"))
os.environ.setdefault(
    "NUMBA_CACHE_DIR", os.path.join(tempfile.gettempdir(),
                                    f"candel_numba_{_USER}"))

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import candel  # noqa: E402
from candel import get_nested  # noqa: E402
from candel.pvdata.field_products import (  # noqa: E402
    field_smoothing_scale_from_config,
    los_field_cache_paths,
    los_radial_grid_payload_from_array,
)

from scripts.preprocess import field_input_cache as cache_mod  # noqa: E402
from scripts.preprocess import field_input_los as los_mod  # noqa: E402


def _split_values(values):
    out = []
    for value in values or []:
        out.extend(v.strip() for v in value.split(",") if v.strip())
    return out


def _read_config_paths(args):
    configs = []
    inputs = [cache_mod._resolve_cli_path(p) for p in args.inputs]
    task_file = args.task_file
    if task_file is None and inputs and cache_mod._looks_like_task_file(
            inputs[0]):
        task_file = inputs.pop(0)

    if task_file is not None:
        task_file = cache_mod._resolve_cli_path(task_file)
        configs.extend(cache_mod._read_task_file(task_file, args.tasks))
    configs.extend(inputs)

    if not configs:
        raise ValueError("provide a task file or at least one config")
    for config_path in configs:
        if not config_path.exists():
            raise FileNotFoundError(config_path)
    return configs


def _smoothing_label(config):
    scale = field_smoothing_scale_from_config(config)
    if scale is None:
        return "none"
    return f"R={scale:g}"


def _config_variants(config_paths):
    variants = []
    seen = set()
    for config_path in config_paths:
        config = candel.load_config(config_path, replace_los_prior=False)
        label = _smoothing_label(config)
        key = (str(config_path), label)
        if key in seen:
            continue
        seen.add(key)
        variants.append({
            "source_path": config_path,
            "config_path": config_path,
            "config": config,
            "smoothing": label,
        })
    return variants


def _infer_h0_los_job(config):
    which_run = get_nested(config, "model/which_run", None)
    if which_run == "CH0":
        return (
            "SH0ES",
            get_nested(config, "io/SH0ES/reconstruction", None),
        )
    if which_run in ("CCHP", "CCHP_CSP"):
        return (
            "CCHP",
            get_nested(config, "io/CCHP/reconstruction", None),
        )
    if which_run in ("EDD_TRGB", "EDD_TRGB_grouped"):
        return (
            which_run,
            get_nested(config, f"io/PV_main/{which_run}/reconstruction", None),
        )
    return None


def _infer_los_jobs(config, catalogue=None, reconstruction=None):
    if catalogue is not None:
        if reconstruction is None:
            h0_job = _infer_h0_los_job(config)
            if h0_job is not None:
                reconstruction = h0_job[1]
        if reconstruction is None:
            raise ValueError(
                "`--reconstruction` is required when `--catalogue` is not "
                "one of the H0 catalogue names inferable from the config.")
        return [{"catalogue": catalogue, "reconstruction": reconstruction}]

    if not get_nested(config, "model/use_reconstruction", False):
        return []

    h0_job = _infer_h0_los_job(config)
    if h0_job is not None:
        catalogue_name, reconstruction_name = h0_job
        if reconstruction_name is None:
            return []
        return [{
            "catalogue": catalogue_name,
            "reconstruction": reconstruction_name,
        }]

    kind = get_nested(config, "pv_model/kind", "")
    if not isinstance(kind, str) or not kind.startswith("precomputed_los_"):
        return []
    reconstruction_name = kind.replace("precomputed_los_", "")
    names = get_nested(config, "io/catalogue_name", [])
    if isinstance(names, str):
        names = [names]
    return [
        {"catalogue": name, "reconstruction": reconstruction_name}
        for name in names
    ]


def _plan_los_metadata(config, catalogue):
    """Return LOS template and count using config-only information."""
    if "random_" in catalogue:
        return config["io"]["los_file_random"], int(
            catalogue.replace("random_", ""))

    if catalogue == "CCHP":
        los_template = get_nested(config, "io/CCHP/los_file", None)
    else:
        los_template = get_nested(
            config, f"io/PV_main/{catalogue}/los_file", None)

    if los_template is None:
        raise ValueError(
            f"No configured LOS template found for `{catalogue}`.")
    return los_template, "-"


def _plan_los_file(variant, job):
    config = variant["config"]
    los_template, n_los = _plan_los_metadata(config, job["catalogue"])
    scale = field_smoothing_scale_from_config(config)
    field_indices = get_nested(config, "io/field_indices", None)
    selected = los_mod._selected_field_indices(
        config, job["reconstruction"], field_indices)
    r = los_mod.radial_los_grid(
        config, job["catalogue"], job["reconstruction"], verbose=False)
    radial_grid = los_radial_grid_payload_from_array(r)
    los_paths = los_field_cache_paths(
        config, job["catalogue"], job["reconstruction"], los_template,
        field_smoothing_scale=scale, field_indices=selected,
        radial_grid=radial_grid)
    if los_paths is None:
        los_paths = [los_mod.resolve_los_output_path(
            los_template, job["reconstruction"], field_smoothing_scale=scale)
        ]
    matches = [
        los_mod.los_file_matches_grid(path, r, verbose=False)
        for path in los_paths
    ]
    status = "cached" if all(matches) else "missing"
    return {
        "catalogue": job["catalogue"],
        "reconstruction": job["reconstruction"],
        "status": status,
        "n_los": n_los,
        "path": los_paths[0] if len(los_paths) == 1 else los_paths,
        "paths": los_paths,
        "path_key": tuple(los_paths),
        "field_indices": selected,
        "r": r,
    }


def _prepare_los(variants, args):
    rows = []
    seen = set()
    for variant in variants:
        jobs = _infer_los_jobs(
            variant["config"], catalogue=args.catalogue,
            reconstruction=args.reconstruction)
        for job in jobs:
            planned = _plan_los_file(variant, job)
            planned["smoothing"] = variant["smoothing"]
            key = (
                planned["catalogue"], planned["reconstruction"],
                planned["smoothing"], planned["path_key"])
            if key in seen:
                for row in rows:
                    row_key = (
                        row["catalogue"], row["reconstruction"],
                        row["smoothing"], row["path_key"])
                    if row_key == key:
                        row["configs"] += 1
                        break
                continue
            seen.add(key)
            if args.plan_only:
                row = planned
            else:
                if planned["status"] == "cached" and not args.overwrite_los:
                    results = [
                        {"path": path, "status": "exists"}
                        for path in planned["paths"]
                    ]
                else:
                    RA, dec, los_template = los_mod.load_los(
                        job["catalogue"], variant["config"],
                        config_path=str(variant["config_path"]))
                    results = []
                    for nsim, path in zip(
                            planned["field_indices"], planned["paths"]):
                        results.append(
                            los_mod.compute_los_file_from_coordinates(
                                job["catalogue"], job["reconstruction"],
                                variant["config"], RA, dec,
                                los_template=los_template,
                                field_smoothing_scale=(
                                    field_smoothing_scale_from_config(
                                        variant["config"])),
                                output_path=path, field_indices=[nsim],
                                overwrite=args.overwrite_los,
                                r=planned["r"]))
                statuses = {result["status"] for result in results}
                status = statuses.pop() if len(statuses) == 1 else "mixed"
                row = {
                    "catalogue": job["catalogue"],
                    "reconstruction": job["reconstruction"],
                    "status": status,
                    "n_los": "",
                    "path": planned["path"],
                    "paths": planned["paths"],
                    "path_key": planned["path_key"],
                }
            row["smoothing"] = variant["smoothing"]
            row["configs"] = 1
            rows.append(row)

    if not rows:
        cache_mod._log("No LOS products inferred for these configs.")
        return

    cache_mod._log("")
    cache_mod._log("Step 1/2: unique LOS products" if args.plan_only
                   else "Step 1/2: LOS preparation result")
    columns = [
        ("catalogue", "catalogue"),
        ("reconstruction", "reconstruction"),
        ("smoothing", "smoothing"),
        ("status", "status"),
        ("n_los", "n_los"),
        ("configs", "configs"),
    ]
    for line in cache_mod._table(rows, columns).splitlines():
        cache_mod._log(line)


def _warm_cache(variants, args):
    selections = _split_values(args.selection)
    cache_mod._install_quiet_reader_logs()
    cache_variants = cache_mod._plan_variants(
        [variant["config_path"] for variant in variants], selections)
    display_config = {
        str(variant["config_path"]): (
            f"{cache_mod._short_path(variant['source_path'])} "
            f"[{variant['smoothing']}]")
        for variant in variants
    }
    for variant in cache_variants:
        variant["config"] = display_config.get(
            str(variant["config_path"]), variant["config"])
    cache_mod._print_plan(cache_variants)

    item_ids = cache_mod._parse_id_spec(args.cache_items)
    try:
        runnable = cache_mod._runnable_variants(cache_variants, item_ids)
    except ValueError as exc:
        raise SystemExit(f"error: {exc}") from None
    if args.plan_only or not runnable:
        if not runnable:
            cache_mod._log("")
            cache_mod._log("Nothing to warm.")
        return

    for i, variant in enumerate(runnable, 1):
        config_path = variant["config_path"]
        selection = variant["selection_override"]
        run_config = config_path
        label = str(config_path)
        if selection is not None:
            label = f"{label} [which_selection={selection}]"
            run_config = cache_mod._write_selection_override(
                config_path, selection)

        cache_mod._log("")
        cache_mod._log(f"[{i}/{len(runnable)}] warming {variant['run']} "
                       f"selection={variant['selection']} from `{label}`.")
        if variant["supersampling"]:
            cache_mod._log(f"  supersampling: {variant['supersampling']}")
        if variant["smoothing"]:
            cache_mod._log(f"  field smoothing: {variant['smoothing']}")
        try:
            summary = cache_mod._load_for_cache(str(run_config))
            cache_mod._log(f"[{i}/{len(runnable)}] done: {summary}")
        finally:
            if selection is not None:
                run_config.unlink(missing_ok=True)


def _mpi_barrier():
    if cache_mod._COMM is not None:
        cache_mod._COMM.Barrier()


def main():
    cache_mod._init_mpi_info()
    parser = argparse.ArgumentParser(
        description="Prepare LOS files and warm 3D volume caches.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent("""\
            Field smoothing is read from model.field_3d_smoothing_scale in
            each input config. Use separate generated configs/tasks for
            multiple smoothing scales.

            examples:
              prepare_field_inputs.py scripts/runs/tasks_TRGBH0_main.txt
              prepare_field_inputs.py config_EDD_TRGB.toml --plan-only
              prepare_field_inputs.py tasks.txt --products cache
              prepare_field_inputs.py tasks.txt --products cache --cache-items 1,3-5
            """))
    parser.add_argument(
        "inputs", nargs="*", type=Path,
        help=("Task file as first argument, or config TOML files to prepare."))
    parser.add_argument("--task-file", type=Path, help=argparse.SUPPRESS)
    parser.add_argument(
        "--tasks", default=None,
        help="Comma-separated task ids/ranges from the task file, e.g. 3,5-8.")
    parser.add_argument(
        "--selection", action="append", default=[],
        help=("Override model.which_selection for H0 cache warming. May be "
              "repeated or comma-separated."))
    parser.add_argument(
        "--cache-items", default=None,
        help=("Comma-separated unique 3D volume-cache item IDs/ranges to warm, "
              "as printed by the plan, e.g. 1,3-5. Default: all missing "
              "unique cache products. LOS products are still prepared first."))
    parser.add_argument(
        "--products", choices=("all", "los", "cache"), default="all",
        help="Which preprocessing products to prepare.")
    parser.add_argument("--catalogue", default=None)
    parser.add_argument("--reconstruction", default=None)
    parser.add_argument(
        "--overwrite-los", action="store_true",
        help="Recompute LOS files even if the target HDF5 file exists.")
    parser.add_argument(
        "--plan-only", action="store_true",
        help="Print planned LOS/cache work and exit without writing files.")
    args = parser.parse_args()

    config_paths = _read_config_paths(args)
    variants = _config_variants(config_paths)

    if args.products in ("all", "los") and cache_mod._RANK == 0:
        _prepare_los(variants, args)
    if args.products in ("all", "los"):
        _mpi_barrier()
    if args.products in ("all", "cache"):
        _warm_cache(variants, args)


if __name__ == "__main__":
    main()
