#!/usr/bin/env python
"""
Prepare reconstruction-derived LOS files and H0 field caches from one command.

This is an orchestration layer around the production preprocessing code: LOS
files use the standard HDF5 schema and cache files are generated by the same
config loaders used by inference.
"""
import argparse
import os
import sys
import tempfile
from pathlib import Path
from textwrap import dedent

# This is a preprocessing script; set before importing candel/JAX.
os.environ.setdefault("JAX_PLATFORMS", "cpu")
_USER = os.environ.get("USER") or "user"
os.environ.setdefault(
    "MPLCONFIGDIR", os.path.join(tempfile.gettempdir(),
                                 f"candel_mpl_{_USER}"))
os.environ.setdefault(
    "NUMBA_CACHE_DIR", os.path.join(tempfile.gettempdir(),
                                    f"candel_numba_{_USER}"))

import tomli_w  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import candel  # noqa: E402
from candel import get_nested  # noqa: E402
from candel.pvdata.field_products import (  # noqa: E402
    density_smoothing_scale_from_config,
    validate_density_smoothing_scale,
)

from scripts.preprocess import field_input_cache as cache_mod  # noqa: E402
from scripts.preprocess import field_input_los as los_mod  # noqa: E402


_USE_CONFIG = object()


def _split_values(values):
    out = []
    for value in values or []:
        out.extend(v.strip() for v in value.split(",") if v.strip())
    return out


def _read_config_paths(args):
    configs = []
    inputs = [cache_mod._resolve_cli_path(p) for p in args.inputs]
    task_file = args.task_file
    if task_file is None and inputs and cache_mod._looks_like_task_file(
            inputs[0]):
        task_file = inputs.pop(0)

    if task_file is not None:
        task_file = cache_mod._resolve_cli_path(task_file)
        configs.extend(cache_mod._read_task_file(task_file, args.tasks))
    configs.extend(inputs)

    if not configs:
        raise ValueError("provide a task file or at least one config")
    for config_path in configs:
        if not config_path.exists():
            raise FileNotFoundError(config_path)
    return configs


def _parse_smoothing_overrides(values):
    tokens = _split_values(values)
    if not tokens:
        return [_USE_CONFIG]

    overrides = []
    for token in tokens:
        lower = token.lower()
        if lower in ("config", "from-config"):
            overrides.append(_USE_CONFIG)
        elif lower in ("none", "off", "unsmoothed", "0"):
            overrides.append(None)
        else:
            overrides.append(validate_density_smoothing_scale(float(token)))
    return overrides


def _apply_smoothing_override(config_path, override):
    config = candel.load_config(config_path, replace_los_prior=False)
    if override is _USE_CONFIG:
        return config_path, None, config

    config.setdefault("model", {})
    if override is None:
        config["model"].pop("density_3d_smoothing_scale", None)
    else:
        config["model"]["density_3d_smoothing_scale"] = float(override)

    tmp = tempfile.NamedTemporaryFile(
        mode="wb", prefix="prepare_field_inputs_", suffix=".toml",
        delete=False)
    with tmp:
        tomli_w.dump(config, tmp)
    return Path(tmp.name), Path(tmp.name), config


def _override_label(config, override):
    if override is _USE_CONFIG:
        scale = density_smoothing_scale_from_config(config)
        if scale is None:
            return "config:none"
        return f"config:R={scale:g}"
    if override is None:
        return "none"
    return f"R={override:g}"


def _config_variants(config_paths, smoothing_overrides):
    variants = []
    seen = set()
    for config_path in config_paths:
        for override in smoothing_overrides:
            run_config, tmp_path, config = _apply_smoothing_override(
                config_path, override)
            label = _override_label(config, override)
            key = (str(config_path), label)
            if key in seen:
                if tmp_path is not None:
                    tmp_path.unlink(missing_ok=True)
                continue
            seen.add(key)
            variants.append({
                "source_path": config_path,
                "config_path": run_config,
                "tmp_path": tmp_path,
                "config": config,
                "smoothing": label,
            })
    return variants


def _infer_h0_los_job(config):
    which_run = get_nested(config, "model/which_run", None)
    if which_run == "CH0":
        return (
            "SH0ES",
            get_nested(config, "io/SH0ES/which_host_los",
                       get_nested(config,
                                  "io/PV_main/SH0ES/which_host_los",
                                  None)),
        )
    if which_run in ("CCHP", "CCHP_CSP"):
        return (
            "CCHP",
            get_nested(config, "io/which_host_los",
                       get_nested(config, "io/CCHP/which_host_los", None)),
        )
    if which_run in ("EDD_TRGB", "EDD_TRGB_grouped"):
        return (
            which_run,
            get_nested(config, "io/which_host_los",
                       get_nested(config,
                                  f"io/PV_main/{which_run}/which_host_los",
                                  None)),
        )
    return None


def _infer_los_jobs(config, catalogue=None, reconstruction=None):
    if catalogue is not None:
        if reconstruction is None:
            h0_job = _infer_h0_los_job(config)
            if h0_job is not None:
                reconstruction = h0_job[1]
        if reconstruction is None:
            raise ValueError(
                "`--reconstruction` is required when `--catalogue` is not "
                "one of the H0 catalogue names inferable from the config.")
        return [{"catalogue": catalogue, "reconstruction": reconstruction}]

    if not get_nested(config, "model/use_reconstruction", False):
        return []

    h0_job = _infer_h0_los_job(config)
    if h0_job is not None:
        catalogue_name, reconstruction_name = h0_job
        if reconstruction_name is None:
            return []
        return [{
            "catalogue": catalogue_name,
            "reconstruction": reconstruction_name,
        }]

    kind = get_nested(config, "pv_model/kind", "")
    if not isinstance(kind, str) or not kind.startswith("precomputed_los_"):
        return []
    reconstruction_name = kind.replace("precomputed_los_", "")
    names = get_nested(config, "io/catalogue_name", [])
    if isinstance(names, str):
        names = [names]
    return [
        {"catalogue": name, "reconstruction": reconstruction_name}
        for name in names
    ]


def _plan_los_file(variant, job):
    config = variant["config"]
    RA, __, los_template = los_mod.load_los(
        job["catalogue"], config, config_path=str(variant["config_path"]))
    scale = density_smoothing_scale_from_config(config)
    los_path = los_mod.resolve_los_output_path(
        los_template, job["reconstruction"],
        density_smoothing_scale=scale)
    status = "cached" if Path(los_path).exists() else "missing"
    return {
        "catalogue": job["catalogue"],
        "reconstruction": job["reconstruction"],
        "status": status,
        "n_los": len(RA),
        "path": los_path,
    }


def _prepare_los(variants, args):
    rows = []
    seen = set()
    for variant in variants:
        jobs = _infer_los_jobs(
            variant["config"], catalogue=args.catalogue,
            reconstruction=args.reconstruction)
        for job in jobs:
            key = (
                str(variant["config_path"]), job["catalogue"],
                job["reconstruction"])
            if key in seen:
                continue
            seen.add(key)
            if args.plan_only:
                row = _plan_los_file(variant, job)
            else:
                result = los_mod.compute_los_file(
                    job["catalogue"], job["reconstruction"],
                    variant["config"], config_path=str(variant["config_path"]),
                    density_smoothing_scale=(
                        density_smoothing_scale_from_config(
                            variant["config"])),
                    overwrite=args.overwrite_los)
                row = {
                    "catalogue": job["catalogue"],
                    "reconstruction": job["reconstruction"],
                    "status": result["status"],
                    "n_los": "",
                    "path": result["path"],
                }
            row["smoothing"] = variant["smoothing"]
            row["config"] = cache_mod._short_path(variant["source_path"])
            rows.append(row)

    if not rows:
        cache_mod._log("No LOS products inferred for these configs.")
        return

    cache_mod._log("")
    cache_mod._log("LOS preparation plan" if args.plan_only
                   else "LOS preparation result")
    columns = [
        ("catalogue", "catalogue"),
        ("reconstruction", "reconstruction"),
        ("smoothing", "smoothing"),
        ("status", "status"),
        ("n_los", "n_los"),
        ("path", "path"),
        ("config", "config"),
    ]
    for line in cache_mod._table(rows, columns).splitlines():
        cache_mod._log(line)


def _warm_cache(variants, args):
    selections = _split_values(args.selection)
    cache_mod._install_quiet_reader_logs()
    cache_variants = cache_mod._plan_variants(
        [variant["config_path"] for variant in variants], selections)
    display_config = {
        str(variant["config_path"]): (
            f"{cache_mod._short_path(variant['source_path'])} "
            f"[{variant['smoothing']}]")
        for variant in variants
    }
    for variant in cache_variants:
        variant["config"] = display_config.get(
            str(variant["config_path"]), variant["config"])
    cache_mod._print_plan(cache_variants)

    runnable = cache_mod._runnable_variants(cache_variants)
    if args.plan_only or not runnable:
        if not runnable:
            cache_mod._log("")
            cache_mod._log("Nothing to warm.")
        return

    for i, variant in enumerate(runnable, 1):
        config_path = variant["config_path"]
        selection = variant["selection_override"]
        run_config = config_path
        label = str(config_path)
        if selection is not None:
            label = f"{label} [which_selection={selection}]"
            run_config = cache_mod._write_selection_override(
                config_path, selection)

        cache_mod._log("")
        cache_mod._log(f"[{i}/{len(runnable)}] warming {variant['run']} "
                       f"selection={variant['selection']} from `{label}`.")
        if variant["supersampling"]:
            cache_mod._log(f"  supersampling: {variant['supersampling']}")
        if variant["smoothing"]:
            cache_mod._log(f"  density smoothing: {variant['smoothing']}")
        try:
            summary = cache_mod._load_for_cache(str(run_config))
            cache_mod._log(f"[{i}/{len(runnable)}] done: {summary}")
        finally:
            if selection is not None:
                run_config.unlink(missing_ok=True)


def _mpi_barrier():
    if cache_mod._COMM is not None:
        cache_mod._COMM.Barrier()


def main():
    cache_mod._init_mpi_info()
    parser = argparse.ArgumentParser(
        description="Prepare LOS files and warm H0 field caches.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent("""\
            examples:
              prepare_field_inputs.py scripts/runs/tasks_TRGBH0_main.txt
              prepare_field_inputs.py config_EDD_TRGB.toml --plan-only
              prepare_field_inputs.py tasks.txt --density-smoothing-scale 2
            """))
    parser.add_argument(
        "inputs", nargs="*", type=Path,
        help=("Task file as first argument, or config TOML files to prepare."))
    parser.add_argument("--task-file", type=Path, help=argparse.SUPPRESS)
    parser.add_argument(
        "--tasks", default=None,
        help="Comma-separated task ids/ranges from the task file, e.g. 3,5-8.")
    parser.add_argument(
        "--selection", action="append", default=[],
        help=("Override model.which_selection for H0 cache warming. May be "
              "repeated or comma-separated."))
    parser.add_argument(
        "--density-smoothing-scale", action="append", default=[],
        help=("Gaussian density smoothing scale(s) in Mpc/h. Use 'none' for "
              "the unsmoothed baseline or omit to use each config as-is. "
              "Each non-zero scale must exceed the field voxel size."))
    parser.add_argument(
        "--products", choices=("all", "los", "cache"), default="all",
        help="Which preprocessing products to prepare.")
    parser.add_argument("--catalogue", default=None)
    parser.add_argument("--reconstruction", default=None)
    parser.add_argument(
        "--overwrite-los", action="store_true",
        help="Recompute LOS files even if the target HDF5 file exists.")
    parser.add_argument(
        "--plan-only", action="store_true",
        help="Print planned LOS/cache work and exit without writing files.")
    args = parser.parse_args()

    tmp_paths = []
    try:
        config_paths = _read_config_paths(args)
        smoothing_overrides = _parse_smoothing_overrides(
            args.density_smoothing_scale)
        variants = _config_variants(config_paths, smoothing_overrides)
        tmp_paths = [
            variant["tmp_path"] for variant in variants
            if variant["tmp_path"] is not None
        ]

        if args.products in ("all", "los") and cache_mod._RANK == 0:
            _prepare_los(variants, args)
        if args.products in ("all", "los"):
            _mpi_barrier()
        if args.products in ("all", "cache"):
            _warm_cache(variants, args)
    finally:
        for path in tmp_paths:
            path.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
