#!/bin/bash -l
#
# Submit CANDEL inference tasks. Cluster (arc, glamdring, or local) is
# picked up from `machine` in local_config.toml via _submit_lib.sh.
# On machine='local' there is no batch backend: -q is rejected and the
# script runs inline (implicit --local).
#
# Task files are generated by generate_tasks.py and have the format:
#   <index> <config_path>

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=../_submit_lib.sh
source "$ROOT/scripts/_submit_lib.sh"

queue=""
ncpu=4
memory=6
gputype=""
gpu_flag=false
no_gpu=false
walltime=""
local_mode=false
dry=false

usage() {
    cat <<EOF
usage: $(basename "$0") -q QUEUE [-n NCPU] [-m MEMORY]
                        [--gpu | --no-gpu] [--gputype TYPE]
                        [--time T] [--local] [--dry] <task_index>

Submit CANDEL inference tasks.

positional:
  task_index              reads tasks_<index>.txt. Suffix 'X' matches
                          tasks_<base>X*.txt (split mode).

options:
  -q, --queue QUEUE       queue/partition (REQUIRED unless --local;
                          rejected when machine='local')
                            glamdring CPU: redwood, berg, cmb
                            glamdring GPU: gpulong, cmbgpu, optgpu
                            arc: short, medium, long
  -n, --ncpu NCPU         number of CPUs (default: $ncpu)
  -m, --memory MEMORY     memory per CPU (GB, default: $memory)
                          total requested = MEMORY * NCPU
  --gpu                   request a GPU (any type). Implicit on arc and on
                          glamdring GPU queues (gpulong/cmbgpu/optgpu).
  --no-gpu                submit as a CPU-only job (overrides arc default).
  --gputype TYPE          specific GPU type. glamdring: selects gputype.
                          arc: selects --gres=gpu:TYPE:1 (implies --gpu).
  --time T                Wall time. Bare integer = hours (arc only).
                          (default on arc: short=12, medium=48, long=required;
                           ignored on glamdring)
  --local                 run inline (login node on clusters;
                          implicit when machine='local')
  --dry                   print submit commands without submitting
EOF
    exit 0
}

task_index=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)       usage ;;
        -q|--queue)      queue="$2"; shift 2 ;;
        -n|--ncpu)       ncpu="$2"; shift 2 ;;
        -m|--memory)     memory="$2"; shift 2 ;;
        --gpu)           gpu_flag=true; shift ;;
        --no-gpu)        no_gpu=true; shift ;;
        --gputype)       gputype="$2"; shift 2 ;;
        --time)          walltime="$2"; shift 2 ;;
        --local)         local_mode=true; shift ;;
        --dry)           dry=true; shift ;;
        *)               task_index="$1"; shift ;;
    esac
done

if [[ -z "$task_index" ]]; then
    echo "[ERROR] Missing task_index"; exit 1
fi
# machine='local' has no batch backend: force --local and reject -q.
if [[ "$CANDEL_CLUSTER" == "local" ]]; then
    if [[ -n "$queue" ]]; then
        echo "[ERROR] machine='local' has no batch backend; -q QUEUE is not valid"; exit 1
    fi
    if ! $local_mode; then
        echo "[INFO] machine='local' — running inline (implicit --local)"
        local_mode=true
    fi
fi
if ! $local_mode && [[ -z "$queue" ]]; then
    echo "[ERROR] -q QUEUE is required (cluster=$CANDEL_CLUSTER)"; exit 1
fi

# GPU policy per cluster. On glamdring, only GPU-named queues imply GPU use
# (explicit --gpu/--gputype also works). On arc, GPU is the default — every
# submission lands on a GPU node unless --no-gpu is passed.
is_gpu=false
case "$CANDEL_CLUSTER" in
    glamdring)
        case "$queue" in
            gpulong|cmbgpu|optgpu) is_gpu=true ;;
        esac
        ;;
    arc)
        is_gpu=true
        ;;
esac
if $gpu_flag || [[ -n "$gputype" ]]; then
    is_gpu=true
fi
if $no_gpu; then
    is_gpu=false
fi

# Resolve task files.
task_files=()
if [[ "$task_index" == *X ]]; then
    while IFS= read -r f; do task_files+=("$f"); done \
        < <(compgen -G "tasks_${task_index}*.txt" | sort -V)
    if (( ${#task_files[@]} == 0 )); then
        echo "[ERROR] No split task files matching: tasks_${task_index}*.txt"; exit 2
    fi
else
    task_files=("tasks_${task_index}.txt")
    [[ -f "${task_files[0]}" ]] || { echo "[ERROR] Task file not found: ${task_files[0]}"; exit 2; }
fi

task_lines=()
task_line_sources=()
for tf in "${task_files[@]}"; do
    while IFS= read -r line || [[ -n "$line" ]]; do
        task_lines+=("$line")
        task_line_sources+=("$tf")
    done < "$tf"
done

if (( CANDEL_USE_FROZEN )); then
    run_root="$CANDEL_FROZEN_ROOT"
    run_main="$run_root/main.py"
    source_label="frozen: $run_root"
else
    run_root="$CANDEL_ROOT"
    run_main="$run_root/scripts/runs/main.py"
    source_label="live:   $run_root"
fi

echo "Task submission ($CANDEL_CLUSTER)"
echo "============================================================"
if $local_mode; then
    echo "  Mode:        LOCAL (login node)"
else
    echo "  Mode:        SUBMIT (queue=$queue)"
fi
total_memory=$(( memory * ncpu ))
echo "  CPUs:        $ncpu"
echo "  Memory:      ${memory} GB/CPU  (total ${total_memory} GB)"
$is_gpu && echo "  GPU:         yes${gputype:+ ($gputype)}"
echo "  Total tasks: ${#task_lines[@]}"
echo "  Source:      $source_label"
echo

echo "Tasks to run:"
for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx=$(echo "$line" | cut -d' ' -f1)
    config_path=$(echo "$line" | cut -d' ' -f2-)
    echo "  - [${task_line_sources[$i]}] Task $idx: $config_path"
done
echo

read -rp "Proceed? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then echo "Aborting."; exit 1; fi

if (( CANDEL_USE_FROZEN )) && [[ ! -d "$run_root" ]]; then
    echo "[ERROR] Frozen package not found: $run_root"
    echo "Run freeze_candel.sh first, or set use_frozen=false in local_config.toml."
    exit 4
fi
export PYTHONPATH="$run_root:${PYTHONPATH:-}"

for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx=$(echo "$line" | cut -d' ' -f1)
    config_path="$CANDEL_ROOT/$(echo "$line" | cut -d' ' -f2-)"

    echo "[INFO] === Task $idx (${task_line_sources[$i]}) ==="
    echo "[INFO] Config: $config_path"
    if [[ ! -f "$config_path" ]]; then
        echo "[WARNING] Config file not found: $config_path"; continue
    fi

    pycmd="$CANDEL_PYTHON $run_main --config $config_path --host-devices $ncpu"

    if $local_mode; then
        echo "[INFO] Running locally..."; echo "  $pycmd"
        eval "$pycmd"
    else
        gpu_flags=()
        if $is_gpu; then
            gpu_flags+=(--gpu)
            [[ -n "$gputype" ]] && gpu_flags+=(--gputype "$gputype")
        fi
        dry_flag=()
        $dry && dry_flag=(--dry)
        time_flag=()
        [[ -n "$walltime" ]] && time_flag=(--time "$walltime")
        submit_job "${gpu_flags[@]}" --queue "$queue" --mem "$total_memory" \
            --cpus "$ncpu" --name "task_${idx}" \
            "${time_flag[@]}" "${dry_flag[@]}" -- $pycmd
    fi
    echo
done

echo "Done."
