#!/bin/bash -l
#
# Submit CANDEL inference tasks. Cluster (arc, glamdring, or local) is
# picked up from `machine` in local_config.toml via _submit_lib.sh.
# On machine='local' there is no batch backend: -q is rejected and the
# script runs inline (implicit --local).
#
# Task files are generated by generate_tasks.py and have the format:
#   <index> <config_path>

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=../_submit_lib.sh
source "$ROOT/scripts/_submit_lib.sh"

queue=""
ncpu=2
memory=7
gputype=""
gpu_mem=""
gpu_flag=false
no_gpu=false
walltime=""
tasks_spec=""
skip_done=false
status_only=false
local_mode=false
dry=false

usage() {
    cat <<EOF
usage: $(basename "$0") -q QUEUE [-n NCPU] [-m MEMORY]
                        [--gpu | --no-gpu] [--gputype TYPE] [--time T]
                        [--tasks SPEC] [--skip-done]
                        [--status] [--local] [--dry] <task_index>

Submit CANDEL inference tasks.

positional:
  task_index              reads tasks_<index>.txt.

options:
  -q, --queue QUEUE       queue/partition (REQUIRED unless --local;
                          rejected when machine='local')
                            glamdring CPU: redwood, berg, cmb
                            glamdring GPU: gpulong, cmbgpu, optgpu
                            arc: short, medium, long
  -n, --ncpu NCPU         number of CPUs (default: $ncpu)
  -m, --memory MEMORY     memory in GB (default: $memory)
                          glamdring GPU: passed directly to addqueue -m;
                          otherwise total requested = MEMORY * NCPU
  --gpu                   request a GPU (any type). Implicit on arc and on
                          glamdring GPU queues (gpulong/cmbgpu/optgpu).
  --no-gpu                submit as a CPU-only job (overrides arc default).
  --gputype TYPE          specific GPU type. glamdring: selects gputype.
                          arc: selects --gres=gpu:TYPE:1 (implies --gpu).
  --gpu-mem GB            Min GPU VRAM in GB (arc only; queries sinfo)
  --time T                Wall time. Bare integer = hours (arc only).
                          (default on arc: short=12, medium=48, long=required;
                           ignored on glamdring)
  --tasks SPEC            Comma-separated task IDs / ranges to submit
                          (e.g. 3,5,7-9). Default: all tasks in the file.
  --skip-done             Skip tasks whose io/fname_output already exists.
  --status                Report done/pending status for each task and exit
                          (no submission). Respects --tasks SPEC. -q is
                          not required in this mode.
  --local                 run inline (login node on clusters;
                          implicit when machine='local')
  --dry                   print submit commands without submitting
EOF
    exit 0
}

task_index=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)       usage ;;
        -q|--queue)      queue="$2"; shift 2 ;;
        -n|--ncpu)       ncpu="$2"; shift 2 ;;
        -m|--memory)     memory="$2"; shift 2 ;;
        --gpu)           gpu_flag=true; shift ;;
        --no-gpu)        no_gpu=true; shift ;;
        --gputype)       gputype="$2"; shift 2 ;;
        --gpu-mem)       gpu_mem="$2"; shift 2 ;;
        --time)          walltime="$2"; shift 2 ;;
        --tasks)         tasks_spec="$2"; shift 2 ;;
        --skip-done)     skip_done=true; shift ;;
        --status)        status_only=true; shift ;;
        --local)         local_mode=true; shift ;;
        --dry)           dry=true; shift ;;
        *)               task_index="$1"; shift ;;
    esac
done

if [[ -z "$task_index" ]]; then
    echo "[ERROR] Missing task_index"; exit 1
fi
# machine='local' has no batch backend: force --local and reject -q.
if [[ "$CANDEL_CLUSTER" == "local" ]]; then
    if [[ -n "$queue" ]]; then
        echo "[ERROR] machine='local' has no batch backend; -q QUEUE is not valid"; exit 1
    fi
    if ! $local_mode; then
        echo "[INFO] machine='local' — running inline (implicit --local)"
        local_mode=true
    fi
fi
if ! $local_mode && ! $status_only && [[ -z "$queue" ]]; then
    echo "[ERROR] -q QUEUE is required (cluster=$CANDEL_CLUSTER)"; exit 1
fi

# Read [io] fname_output from a task's TOML (section-aware, unquoted).
_read_fname_output() {
    awk '
        /^\[io\][[:space:]]*$/ { in_io=1; next }
        /^\[/                  { in_io=0 }
        in_io && /^[[:space:]]*fname_output[[:space:]]*=/ {
            line = $0
            sub(/^[^=]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*(#.*)?$/, "", line)
            gsub(/^["'\'']|["'\'']$/, "", line)
            print line
            exit
        }
    ' "$1"
}

# Resolve io/fname_output against root_results from local_config.toml.
_resolved_output() {
    local cfg_rel="$1"
    local cfg_abs="$CANDEL_ROOT/$cfg_rel"
    [[ -f "$cfg_abs" ]] || { echo ""; return; }
    local fname; fname=$(_read_fname_output "$cfg_abs")
    [[ -z "$fname" ]] && { echo ""; return; }
    if [[ "$fname" = /* ]]; then
        echo "$fname"; return
    fi
    local root; root=$(_toml_get root_results "$CANDEL_ROOT/local_config.toml")
    if [[ -z "$root" ]]; then
        root=$(_toml_get root_main "$CANDEL_ROOT/local_config.toml")
        root="${root%/}/results"
    fi
    echo "${root%/}/$fname"
}

# GPU policy per cluster. On glamdring, only GPU-named queues imply GPU use
# (explicit --gpu/--gputype also works). On arc, GPU is the default — every
# submission lands on a GPU node unless --no-gpu is passed.
is_gpu=false
case "$CANDEL_CLUSTER" in
    glamdring)
        case "$queue" in
            gpulong|cmbgpu|optgpu) is_gpu=true ;;
        esac
        ;;
    arc)
        is_gpu=true
        ;;
esac
if $gpu_flag || [[ -n "$gputype" ]] || [[ -n "$gpu_mem" ]]; then
    is_gpu=true
fi
if $no_gpu; then
    is_gpu=false
fi

# Resolve the single task file.
task_file="tasks_${task_index}.txt"
[[ -f "$task_file" ]] || { echo "[ERROR] Task file not found: $task_file"; exit 2; }

# Parse --tasks SPEC ("3,5,7-9") into the allowed-id set. Stored as a
# space-padded string for portable substring membership tests on bash 3.2.
allowed_ids=" "
allowed_any=true
if [[ -n "$tasks_spec" ]]; then
    allowed_any=false
    IFS=',' read -ra _parts <<< "$tasks_spec"
    for p in "${_parts[@]}"; do
        [[ -z "$p" ]] && continue
        if [[ "$p" == *-* ]]; then
            _lo=${p%-*}; _hi=${p#*-}
            for ((i=_lo; i<=_hi; i++)); do allowed_ids+="$i "; done
        else
            allowed_ids+="$p "
        fi
    done
fi

# Walk the task file once, filtering by --tasks and resolving output paths
# so --skip-done and --status don't need a second pass.
task_lines=()
task_outputs=()
task_done=()
total_in_file=0
n_done_in_scope=0
while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    total_in_file=$((total_in_file + 1))
    id=${line%% *}
    cfg_rel=${line#* }
    if ! $allowed_any && [[ "$allowed_ids" != *" $id "* ]]; then continue; fi
    out=$(_resolved_output "$cfg_rel")
    if [[ -n "$out" && -f "$out" ]]; then
        done_flag=1
        n_done_in_scope=$((n_done_in_scope + 1))
    else
        done_flag=0
    fi
    task_lines+=("$line")
    task_outputs+=("$out")
    task_done+=("$done_flag")
done < "$task_file"

# --status: print per-task report and exit.
if $status_only; then
    n_total_in_scope=${#task_lines[@]}
    for i in "${!task_lines[@]}"; do
        id=${task_lines[$i]%% *}
        if [[ "${task_done[$i]}" == 1 ]]; then
            echo "  [done]    task $id: ${task_outputs[$i]}"
        else
            out="${task_outputs[$i]:-<unresolved>}"
            echo "  [pending] task $id: $out"
        fi
    done
    echo
    echo "$n_done_in_scope/$n_total_in_scope done"
    exit 0
fi

# --skip-done: drop the rows whose output exists.
if $skip_done; then
    filtered_lines=()
    for i in "${!task_lines[@]}"; do
        id=${task_lines[$i]%% *}
        if [[ "${task_done[$i]}" == 1 ]]; then
            echo "[SKIP] task $id: output exists (${task_outputs[$i]})"
            continue
        fi
        filtered_lines+=("${task_lines[$i]}")
    done
    task_lines=("${filtered_lines[@]}")
fi

if (( ${#task_lines[@]} == 0 )); then
    echo "[INFO] No tasks to submit after filtering."; exit 0
fi

if (( CANDEL_USE_FROZEN )); then
    run_root="$CANDEL_FROZEN_ROOT"
    run_main="$run_root/main.py"
    source_label="frozen: $run_root"
else
    run_root="$CANDEL_ROOT"
    run_main="$run_root/scripts/runs/main.py"
    source_label="live:   $run_root"
fi

echo "Task submission ($CANDEL_CLUSTER)"
echo "============================================================"
if $local_mode; then
    echo "  Mode:        LOCAL (login node)"
else
    echo "  Mode:        SUBMIT (queue=$queue)"
fi
total_memory=$(( memory * ncpu ))
submit_memory=$total_memory
host_devices=$ncpu
if $is_gpu; then
    if [[ "$CANDEL_CLUSTER" == "glamdring" ]]; then
        submit_memory=$memory
    fi
    host_devices=1
fi
echo "  CPUs:        $ncpu"
echo "  Memory:      ${submit_memory} GB requested"
$is_gpu && echo "  GPU:         yes${gputype:+ ($gputype)}"
echo "  Host devices: $host_devices"
if (( ${#task_lines[@]} != total_in_file )); then
    echo "  Total tasks: ${#task_lines[@]} (of $total_in_file in $task_file)"
else
    echo "  Total tasks: ${#task_lines[@]}"
fi
echo "  Source:      $source_label"
echo

echo "Tasks to run:"
for line in "${task_lines[@]}"; do
    idx=${line%% *}
    config_path=${line#* }
    echo "  - Task $idx: $config_path"
done
echo

read -rp "Proceed? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then echo "Aborting."; exit 1; fi

if (( CANDEL_USE_FROZEN )) && [[ ! -d "$run_root" ]]; then
    echo "[ERROR] Frozen package not found: $run_root"
    echo "Run freeze_candel.sh first, or set use_frozen=false in local_config.toml."
    exit 4
fi
export PYTHONPATH="$run_root:${PYTHONPATH:-}"

for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx=$(echo "$line" | cut -d' ' -f1)
    config_path="$CANDEL_ROOT/$(echo "$line" | cut -d' ' -f2-)"

    echo "[INFO] === Task $idx ==="
    echo "[INFO] Config: $config_path"
    if [[ ! -f "$config_path" ]]; then
        echo "[WARNING] Config file not found: $config_path"; continue
    fi

    pycmd="$CANDEL_PYTHON $run_main --config $config_path --host-devices $host_devices"

    if $local_mode; then
        echo "[INFO] Running locally..."; echo "  $pycmd"
        eval "$pycmd"
    else
        gpu_flags=()
        if $is_gpu; then
            gpu_flags+=(--gpu)
            [[ -n "$gputype" ]] && gpu_flags+=(--gputype "$gputype")
            [[ -n "$gpu_mem" ]] && gpu_flags+=(--gpu-mem "$gpu_mem")
        fi
        dry_flag=()
        $dry && dry_flag=(--dry)
        time_flag=()
        [[ -n "$walltime" ]] && time_flag=(--time "$walltime")
        submit_job "${gpu_flags[@]}" --queue "$queue" --mem "$submit_memory" \
            --cpus "$ncpu" --name "task_${idx}" \
            "${time_flag[@]}" "${dry_flag[@]}" -- $pycmd
    fi
    echo
done

echo "Done."
