#!/bin/bash -l
#
# Submit CANDEL inference tasks. Cluster (arc, glamdring, or local) is
# picked up from `machine` in local_config.toml via _submit_lib.sh.
# On machine='local' there is no batch backend: -q is rejected and the
# script runs inline (implicit --local).
#
# Task files are generated by generate_tasks.py and have the format:
#   <index> <config_path>

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=../_submit_lib.sh
source "$ROOT/scripts/_submit_lib.sh"

queue=""
ncpu=2
memory=7
gputype=""
gpu_mem=""
gpu_flag=false
no_gpu=false
walltime=""
tasks_spec=""
batch_size=0
batch_arg_set=false
skip_done=false
status_only=false
local_mode=false
dry=false
trgb_ppc=false
trgb_ppc_field_indices="random"
trgb_ppc_n_workers=""
trgb_ppc_n_ppc=""
trgb_ppc_seed=42

usage() {
    cat <<EOF
usage: $(basename "$0") -q QUEUE [-n NCPU] [-m MEMORY]
                        [--gpu | --no-gpu] [--gputype TYPE] [--time T]
                        [--tasks SPEC] [--batch N] [--skip-done]
                        [--trgb-ppc] [--status] [--local] [--dry]
                        <task_index>

Submit CANDEL inference tasks.

positional:
  task_index              reads tasks_<index>.txt.

options:
  -q, --queue QUEUE       queue/partition (REQUIRED unless --local;
                          rejected when machine='local')
                            glamdring CPU: redwood, berg, cmb
                            glamdring GPU: gpulong, cmbgpu, optgpu
                            arc: short, medium, long
  -n, --ncpu NCPU         number of CPUs (default: $ncpu)
  -m, --memory MEMORY     memory in GB (default: $memory)
                          glamdring GPU: passed directly to addqueue -m;
                          otherwise total requested = MEMORY * NCPU
  --gpu                   request a GPU (any type). Implicit on arc and on
                          glamdring GPU queues (gpulong/cmbgpu/optgpu).
  --no-gpu                submit as a CPU-only job (overrides arc default).
  --gputype TYPE          specific GPU type. glamdring: selects gputype.
                          arc: selects --gres=gpu:TYPE:1 (implies --gpu).
  --gpu-mem GB            Min GPU VRAM in GB (arc only; queries sinfo)
  --time T                Wall time. Bare integer = hours (arc only).
                          (default on arc: short=12, medium=48, long=required;
                           ignored on glamdring)
  --tasks SPEC            Comma-separated task IDs / ranges to submit
                          (e.g. 3,5,7-9). Default: all tasks in the file.
  --batch N               Submit chunks of N tasks per scheduler job. Tasks
                          run sequentially inside the job, with one log file
                          per task named logs-<jobid>-task_<id>.out, and
                          later tasks still run if one fails.
  --skip-done             Skip tasks whose io/fname_output already exists.
  --trgb-ppc              After a successful EDD_TRGB/EDD_TRGB_grouped task,
                          try to run scripts/mocks/ppc_TRGB.py on the
                          posterior. PPC failures are logged but do not mark
                          the inference task failed.
  --trgb-ppc-field-indices SPEC
                          PPC field selection: random, all, 0-29, or comma
                          list. Default: $trgb_ppc_field_indices.
  --trgb-ppc-n-workers N  PPC worker processes. Default: --ncpu.
  --trgb-ppc-n-ppc N      Number of simulated PPC hosts.
  --trgb-ppc-seed S       PPC random seed. Default: $trgb_ppc_seed.
  --status                Report done/pending status for each task and exit
                          (no submission). Respects --tasks SPEC. -q is
                          not required in this mode.
  --local                 run inline (login node on clusters;
                          implicit when machine='local')
  --dry                   print submit commands without submitting
EOF
    exit 0
}

task_index=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)       usage ;;
        -q|--queue)      queue="$2"; shift 2 ;;
        -n|--ncpu)       ncpu="$2"; shift 2 ;;
        -m|--memory)     memory="$2"; shift 2 ;;
        --gpu)           gpu_flag=true; shift ;;
        --no-gpu)        no_gpu=true; shift ;;
        --gputype)       gputype="$2"; shift 2 ;;
        --gpu-mem)       gpu_mem="$2"; shift 2 ;;
        --time)          walltime="$2"; shift 2 ;;
        --tasks)         tasks_spec="$2"; shift 2 ;;
        --batch)         batch_arg_set=true; batch_size="$2"; shift 2 ;;
        --skip-done)     skip_done=true; shift ;;
        --status)        status_only=true; shift ;;
        --local)         local_mode=true; shift ;;
        --dry)           dry=true; shift ;;
        --trgb-ppc)      trgb_ppc=true; shift ;;
        --trgb-ppc-field-indices)
                         trgb_ppc_field_indices="$2"; shift 2 ;;
        --trgb-ppc-n-workers)
                         trgb_ppc_n_workers="$2"; shift 2 ;;
        --trgb-ppc-n-ppc)
                         trgb_ppc_n_ppc="$2"; shift 2 ;;
        --trgb-ppc-seed)
                         trgb_ppc_seed="$2"; shift 2 ;;
        *)               task_index="$1"; shift ;;
    esac
done

if [[ -z "$task_index" ]]; then
    echo "[ERROR] Missing task_index"; exit 1
fi
if ! [[ "$batch_size" =~ ^[0-9]+$ ]]; then
    echo "[ERROR] --batch must be a positive integer"; exit 1
fi
if $batch_arg_set && (( batch_size < 1 )); then
    echo "[ERROR] --batch must be a positive integer"; exit 1
fi
if ! $batch_arg_set; then
    batch_mode=false
else
    batch_mode=true
fi
if [[ -z "$trgb_ppc_n_workers" ]]; then
    trgb_ppc_n_workers="$ncpu"
fi
if ! [[ "$trgb_ppc_n_workers" =~ ^[0-9]+$ ]] || (( trgb_ppc_n_workers < 1 )); then
    echo "[ERROR] --trgb-ppc-n-workers must be a positive integer"; exit 1
fi
if [[ -n "$trgb_ppc_n_ppc" ]] \
        && { ! [[ "$trgb_ppc_n_ppc" =~ ^[0-9]+$ ]] || (( trgb_ppc_n_ppc < 1 )); }; then
    echo "[ERROR] --trgb-ppc-n-ppc must be a positive integer"; exit 1
fi
if ! [[ "$trgb_ppc_seed" =~ ^-?[0-9]+$ ]]; then
    echo "[ERROR] --trgb-ppc-seed must be an integer"; exit 1
fi
# machine='local' has no batch backend: force --local and reject -q.
if [[ "$CANDEL_CLUSTER" == "local" ]]; then
    if [[ -n "$queue" ]]; then
        echo "[ERROR] machine='local' has no batch backend; -q QUEUE is not valid"; exit 1
    fi
    if ! $local_mode; then
        echo "[INFO] machine='local' — running inline (implicit --local)"
        local_mode=true
    fi
fi
if ! $local_mode && ! $status_only && [[ -z "$queue" ]]; then
    echo "[ERROR] -q QUEUE is required (cluster=$CANDEL_CLUSTER)"; exit 1
fi

# Read [io] fname_output from a task's TOML (section-aware, unquoted).
_read_fname_output() {
    awk '
        /^\[io\][[:space:]]*$/ { in_io=1; next }
        /^\[/                  { in_io=0 }
        in_io && /^[[:space:]]*fname_output[[:space:]]*=/ {
            line = $0
            sub(/^[^=]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*(#.*)?$/, "", line)
            gsub(/^["'\'']|["'\'']$/, "", line)
            print line
            exit
        }
    ' "$1"
}

# Resolve io/fname_output against root_results from local_config.toml.
_resolved_output() {
    local cfg_rel="$1"
    local cfg_abs="$CANDEL_ROOT/$cfg_rel"
    [[ -f "$cfg_abs" ]] || { echo ""; return; }
    local fname; fname=$(_read_fname_output "$cfg_abs")
    [[ -z "$fname" ]] && { echo ""; return; }
    if [[ "$fname" = /* ]]; then
        echo "$fname"; return
    fi
    local root; root=$(_toml_get root_results "$CANDEL_ROOT/local_config.toml")
    if [[ -z "$root" ]]; then
        root=$(_toml_get root_main "$CANDEL_ROOT/local_config.toml")
        root="${root%/}/results"
    fi
    echo "${root%/}/$fname"
}

_read_model_which_run() {
    awk '
        /^\[model\][[:space:]]*$/ { in_model=1; next }
        /^\[/                     { in_model=0 }
        in_model && /^[[:space:]]*which_run[[:space:]]*=/ {
            line = $0
            sub(/^[^=]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*(#.*)?$/, "", line)
            gsub(/^["'\'']|["'\'']$/, "", line)
            print line
            exit
        }
    ' "$1"
}

_run_trgb_ppc() {
    local task_id="$1" config_path="$2" posterior="$3"
    $trgb_ppc || return 0

    local which_run; which_run=$(_read_model_which_run "$config_path")
    case "$which_run" in
        EDD_TRGB|EDD_TRGB_grouped) ;;
        *)
            echo "[INFO] task $task_id: --trgb-ppc skipped for which_run=${which_run:-<unset>}"
            return 0 ;;
    esac

    if [[ -z "$posterior" || ! -f "$posterior" ]]; then
        echo "[WARNING] task $task_id: TRGB PPC skipped; posterior not found: ${posterior:-<unresolved>}"
        return 0
    fi

    local -a ppc_cmd=(
        "$CANDEL_PYTHON" -u "$CANDEL_ROOT/scripts/mocks/ppc_TRGB.py"
        --config "$config_path"
        --posterior "$posterior"
        --seed "$trgb_ppc_seed"
        --field-indices "$trgb_ppc_field_indices"
        --n-workers "$trgb_ppc_n_workers"
    )
    if [[ -n "$trgb_ppc_n_ppc" ]]; then
        ppc_cmd+=(--n-ppc "$trgb_ppc_n_ppc")
    fi

    echo "[INFO] task $task_id: running TRGB PPC"
    echo "[INFO] PPC posterior: $posterior"
    if "${ppc_cmd[@]}"; then
        echo "[OK] task $task_id: TRGB PPC complete"
    else
        echo "[WARNING] task $task_id: TRGB PPC failed; inference result kept"
    fi
}

_emit_task_runner_helpers() {
    cat <<'SCRIPT'
_read_model_which_run() {
    awk '
        /^\[model\][[:space:]]*$/ { in_model=1; next }
        /^\[/                     { in_model=0 }
        in_model && /^[[:space:]]*which_run[[:space:]]*=/ {
            line = $0
            sub(/^[^=]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*(#.*)?$/, "", line)
            gsub(/^["'\'']|["'\'']$/, "", line)
            print line
            exit
        }
    ' "$1"
}

_run_trgb_ppc() {
    local task_id="$1" config_path="$2" posterior="$3"
    [[ "$TRGB_PPC" == 1 ]] || return 0

    local which_run; which_run=$(_read_model_which_run "$config_path")
    case "$which_run" in
        EDD_TRGB|EDD_TRGB_grouped) ;;
        *)
            echo "[INFO] task $task_id: --trgb-ppc skipped for which_run=${which_run:-<unset>}"
            return 0 ;;
    esac

    if [[ -z "$posterior" || ! -f "$posterior" ]]; then
        echo "[WARNING] task $task_id: TRGB PPC skipped; posterior not found: ${posterior:-<unresolved>}"
        return 0
    fi

    local -a ppc_cmd=(
        "$CANDEL_PYTHON" -u "$CANDEL_ROOT/scripts/mocks/ppc_TRGB.py"
        --config "$config_path"
        --posterior "$posterior"
        --seed "$TRGB_PPC_SEED"
        --field-indices "$TRGB_PPC_FIELD_INDICES"
        --n-workers "$TRGB_PPC_N_WORKERS"
    )
    if [[ -n "$TRGB_PPC_N_PPC" ]]; then
        ppc_cmd+=(--n-ppc "$TRGB_PPC_N_PPC")
    fi

    echo "[INFO] task $task_id: running TRGB PPC"
    echo "[INFO] PPC posterior: $posterior"
    if "${ppc_cmd[@]}"; then
        echo "[OK] task $task_id: TRGB PPC complete"
    else
        echo "[WARNING] task $task_id: TRGB PPC failed; inference result kept"
    fi
}

_run_inference_task() {
    local task_id="$1" config_path="$2" posterior="$3"
    export PYTHONPATH="$RUN_ROOT:${PYTHONPATH:-}"
    "$CANDEL_PYTHON" -u "$RUN_MAIN" --config "$config_path" \
        --host-devices "$HOST_DEVICES" || return $?
    _run_trgb_ppc "$task_id" "$config_path" "$posterior"
}
SCRIPT
}

# GPU policy per cluster. On glamdring, only GPU-named queues imply GPU use
# (explicit --gpu/--gputype also works). On arc, GPU is the default — every
# submission lands on a GPU node unless --no-gpu is passed.
is_gpu=false
case "$CANDEL_CLUSTER" in
    glamdring)
        case "$queue" in
            gpulong|cmbgpu|optgpu) is_gpu=true ;;
        esac
        ;;
    arc)
        is_gpu=true
        ;;
esac
if $gpu_flag || [[ -n "$gputype" ]] || [[ -n "$gpu_mem" ]]; then
    is_gpu=true
fi
if $no_gpu; then
    is_gpu=false
fi

# Resolve the single task file.
task_file="tasks_${task_index}.txt"
[[ -f "$task_file" ]] || { echo "[ERROR] Task file not found: $task_file"; exit 2; }

# Parse --tasks SPEC ("3,5,7-9") into the allowed-id set. Stored as a
# space-padded string for portable substring membership tests on bash 3.2.
allowed_ids=" "
allowed_any=true
if [[ -n "$tasks_spec" ]]; then
    allowed_any=false
    IFS=',' read -ra _parts <<< "$tasks_spec"
    for p in "${_parts[@]}"; do
        [[ -z "$p" ]] && continue
        if [[ "$p" == *-* ]]; then
            _lo=${p%-*}; _hi=${p#*-}
            for ((i=_lo; i<=_hi; i++)); do allowed_ids+="$i "; done
        else
            allowed_ids+="$p "
        fi
    done
fi

# Walk the task file once, filtering by --tasks and resolving output paths
# for --skip-done and --status.
task_lines=()
task_outputs=()
task_done=()
total_in_file=0
n_done_in_scope=0
while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    total_in_file=$((total_in_file + 1))
    id=${line%% *}
    cfg_rel=${line#* }
    if ! $allowed_any && [[ "$allowed_ids" != *" $id "* ]]; then continue; fi
    out=$(_resolved_output "$cfg_rel")
    if [[ -n "$out" && -f "$out" ]]; then
        done_flag=1
        n_done_in_scope=$((n_done_in_scope + 1))
    else
        done_flag=0
    fi
    task_lines+=("$line")
    task_outputs+=("$out")
    task_done+=("$done_flag")
done < "$task_file"

# --status: print per-task report and exit.
if $status_only; then
    n_total_in_scope=${#task_lines[@]}
    for i in "${!task_lines[@]}"; do
        id=${task_lines[$i]%% *}
        if [[ "${task_done[$i]}" == 1 ]]; then
            echo "  [done]    task $id: ${task_outputs[$i]}"
        else
            out="${task_outputs[$i]:-<unresolved>}"
            echo "  [pending] task $id: $out"
        fi
    done
    echo
    echo "$n_done_in_scope/$n_total_in_scope done"
    exit 0
fi

# --skip-done: drop the rows whose output exists.
if $skip_done; then
    filtered_lines=()
    filtered_outputs=()
    filtered_done=()
    for i in "${!task_lines[@]}"; do
        id=${task_lines[$i]%% *}
        if [[ "${task_done[$i]}" == 1 ]]; then
            echo "[SKIP] task $id: output exists (${task_outputs[$i]})"
            continue
        fi
        filtered_lines+=("${task_lines[$i]}")
        filtered_outputs+=("${task_outputs[$i]}")
        filtered_done+=("${task_done[$i]}")
    done
    task_lines=("${filtered_lines[@]}")
    task_outputs=("${filtered_outputs[@]}")
    task_done=("${filtered_done[@]}")
fi

if (( ${#task_lines[@]} == 0 )); then
    echo "[INFO] No tasks to submit after filtering."; exit 0
fi

if (( CANDEL_USE_FROZEN )); then
    run_root="$CANDEL_FROZEN_ROOT"
    run_main="$run_root/main.py"
    source_label="frozen: $run_root"
else
    run_root="$CANDEL_ROOT"
    run_main="$run_root/scripts/runs/main.py"
    source_label="live:   $run_root"
fi

echo "Task submission ($CANDEL_CLUSTER)"
echo "============================================================"
if $local_mode; then
    echo "  Mode:        LOCAL (login node)"
else
    echo "  Mode:        SUBMIT (queue=$queue)"
fi
total_memory=$(( memory * ncpu ))
submit_memory=$total_memory
host_devices=$ncpu
if $is_gpu; then
    if [[ "$CANDEL_CLUSTER" == "glamdring" ]]; then
        submit_memory=$memory
    fi
    host_devices=1
fi
echo "  CPUs:        $ncpu"
echo "  Memory:      ${submit_memory} GB requested"
$is_gpu && echo "  GPU:         yes${gputype:+ ($gputype)}"
echo "  Host devices: $host_devices"
$trgb_ppc && {
    echo "  TRGB PPC:    yes"
    echo "    fields:    $trgb_ppc_field_indices"
    echo "    workers:   $trgb_ppc_n_workers"
    [[ -n "$trgb_ppc_n_ppc" ]] && echo "    n_ppc:     $trgb_ppc_n_ppc"
}
if (( ${#task_lines[@]} != total_in_file )); then
    echo "  Total tasks: ${#task_lines[@]} (of $total_in_file in $task_file)"
else
    echo "  Total tasks: ${#task_lines[@]}"
fi
if $batch_mode; then
    n_batches=$(( (${#task_lines[@]} + batch_size - 1) / batch_size ))
    echo "  Batch size:  $batch_size"
    echo "  Batch jobs:  $n_batches"
fi
echo "  Source:      $source_label"
echo

echo "Tasks to run:"
for line in "${task_lines[@]}"; do
    idx=${line%% *}
    config_path=${line#* }
    echo "  - Task $idx: $config_path"
done
echo

read -rp "Proceed? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then echo "Aborting."; exit 1; fi

if (( CANDEL_USE_FROZEN )) && [[ ! -d "$run_root" ]]; then
    echo "[ERROR] Frozen package not found: $run_root"
    echo "Run freeze_candel.sh first, or set use_frozen=false in local_config.toml."
    exit 4
fi
export PYTHONPATH="$run_root:${PYTHONPATH:-}"
runner_ext=".sh"
[[ "$CANDEL_CLUSTER" == "glamdring" ]] && runner_ext=""

_write_batch_runner() {
    local runner="$1" batch_label="$2" log_dir="$3"
    local start="$4" end="$5"

    mkdir -p "$(dirname "$runner")"
    {
        printf '#!/bin/bash -l\n'
        printf 'set -uo pipefail\n'
        printf 'CANDEL_ROOT=%q\n' "$CANDEL_ROOT"
        printf 'CANDEL_PYTHON=%q\n' "$CANDEL_PYTHON"
        printf 'RUN_ROOT=%q\n' "$run_root"
        printf 'RUN_MAIN=%q\n' "$run_main"
        printf 'SUBMIT_CWD=%q\n' "$PWD"
        printf 'HOST_DEVICES=%q\n' "$host_devices"
        printf 'BATCH_LABEL=%q\n' "$batch_label"
        printf 'LOG_DIR=%q\n' "$log_dir"
        if $trgb_ppc; then
            printf 'TRGB_PPC=1\n'
        else
            printf 'TRGB_PPC=0\n'
        fi
        printf 'TRGB_PPC_FIELD_INDICES=%q\n' "$trgb_ppc_field_indices"
        printf 'TRGB_PPC_N_WORKERS=%q\n' "$trgb_ppc_n_workers"
        printf 'TRGB_PPC_N_PPC=%q\n' "$trgb_ppc_n_ppc"
        printf 'TRGB_PPC_SEED=%q\n' "$trgb_ppc_seed"
        printf 'batch_tasks=()\n'
        printf 'batch_outputs=()\n'
        for ((j=start; j<end; j++)); do
            printf 'batch_tasks+=(%q)\n' "${task_lines[$j]}"
            printf 'batch_outputs+=(%q)\n' "${task_outputs[$j]}"
        done
        cat <<'SCRIPT'

mkdir -p "$LOG_DIR"
cd "$SUBMIT_CWD"
export PYTHONPATH="$RUN_ROOT:${PYTHONPATH:-}"
SCRIPT
        _emit_task_runner_helpers
        cat <<'SCRIPT'

job_id="${SLURM_JOB_ID:-${SLURM_JOBID:-${JOB_ID:-local_$$}}}"
status_file="$LOG_DIR/logs-${job_id}-batch_${BATCH_LABEL}.status.tsv"
printf 'task_id\tstatus\texit_code\tlog\tconfig\n' > "$status_file"

echo "[INFO] Batch $BATCH_LABEL"
echo "[INFO] Logs: $LOG_DIR/logs-${job_id}-task_<id>.out"

failed=0
succeeded=0
for k in "${!batch_tasks[@]}"; do
    line="${batch_tasks[$k]}"
    posterior="${batch_outputs[$k]}"
    idx="${line%% *}"
    cfg_rel="${line#* }"
    config_path="$CANDEL_ROOT/$cfg_rel"
    task_log="$LOG_DIR/logs-${job_id}-task_${idx}.out"

    {
        echo "[INFO] Task $idx"
        echo "[INFO] Config: $config_path"
        echo "[INFO] Started: $(date -Is)"
    } > "$task_log"

    echo "[INFO] === Task $idx ==="
    echo "[INFO] task log: $task_log"

    if [[ ! -f "$config_path" ]]; then
        echo "[ERROR] Config file not found: $config_path" | tee -a "$task_log"
        printf '%s\tfailed\t2\t%s\t%s\n' "$idx" "$task_log" "$config_path" >> "$status_file"
        failed=$((failed + 1))
        continue
    fi

    if _run_inference_task "$idx" "$config_path" "$posterior" >> "$task_log" 2>&1
    then
        echo "[INFO] Finished: $(date -Is)" >> "$task_log"
        echo "[OK] task $idx"
        printf '%s\tok\t0\t%s\t%s\n' "$idx" "$task_log" "$config_path" >> "$status_file"
        succeeded=$((succeeded + 1))
    else
        rc=$?
        echo "[ERROR] Failed with exit code $rc at $(date -Is)" >> "$task_log"
        echo "[FAIL] task $idx exit=$rc"
        printf '%s\tfailed\t%s\t%s\t%s\n' "$idx" "$rc" "$task_log" "$config_path" >> "$status_file"
        failed=$((failed + 1))
    fi
done

echo "[INFO] Batch $BATCH_LABEL complete: $succeeded ok, $failed failed"
echo "[INFO] Status: $status_file"
if (( failed > 0 )); then
    exit 1
fi
SCRIPT
    } > "$runner"
    chmod +x "$runner"
}

_write_single_runner() {
    local runner="$1" idx="$2" config_path="$3" posterior="$4"

    mkdir -p "$(dirname "$runner")"
    {
        printf '#!/bin/bash -l\n'
        printf 'set -euo pipefail\n'
        printf 'CANDEL_ROOT=%q\n' "$CANDEL_ROOT"
        printf 'CANDEL_PYTHON=%q\n' "$CANDEL_PYTHON"
        printf 'RUN_ROOT=%q\n' "$run_root"
        printf 'RUN_MAIN=%q\n' "$run_main"
        printf 'HOST_DEVICES=%q\n' "$host_devices"
        if $trgb_ppc; then
            printf 'TRGB_PPC=1\n'
        else
            printf 'TRGB_PPC=0\n'
        fi
        printf 'TRGB_PPC_FIELD_INDICES=%q\n' "$trgb_ppc_field_indices"
        printf 'TRGB_PPC_N_WORKERS=%q\n' "$trgb_ppc_n_workers"
        printf 'TRGB_PPC_N_PPC=%q\n' "$trgb_ppc_n_ppc"
        printf 'TRGB_PPC_SEED=%q\n' "$trgb_ppc_seed"
        _emit_task_runner_helpers
        printf '_run_inference_task %q %q %q\n' \
            "$idx" "$config_path" "$posterior"
    } > "$runner"
    chmod +x "$runner"
}

if $batch_mode; then
    stamp="$(date +%Y%m%d_%H%M%S)_$$"
    batch_script_root="$PWD/generated_batch_scripts/${task_index}/${stamp}"
    local_failed=0

    for ((start=0; start<${#task_lines[@]}; start+=batch_size)); do
        end=$((start + batch_size))
        (( end > ${#task_lines[@]} )) && end=${#task_lines[@]}
        first_id=${task_lines[$start]%% *}
        last_id=${task_lines[$((end - 1))]%% *}
        batch_label=$(printf '%04d-%04d' "$first_id" "$last_id")
        batch_job_name="task_${first_id}_batch_${batch_label}"
        runner="$batch_script_root/batch_${batch_label}${runner_ext}"
        batch_log_dir="$PWD"

        _write_batch_runner "$runner" "$batch_label" "$batch_log_dir" \
            "$start" "$end"

        echo "[INFO] === Batch $batch_label ==="
        echo "[INFO] Tasks: $first_id-$last_id"
        echo "[INFO] Runner: $runner"
        echo "[INFO] Per-task logs: $batch_log_dir/logs-<jobid>-task_<id>.out"

        if $local_mode; then
            echo "[INFO] Running batch locally..."; echo "  $runner"
            if ! "$runner"; then
                local_failed=1
            fi
        else
            gpu_flags=()
            if $is_gpu; then
                gpu_flags+=(--gpu)
                [[ -n "$gputype" ]] && gpu_flags+=(--gputype "$gputype")
                [[ -n "$gpu_mem" ]] && gpu_flags+=(--gpu-mem "$gpu_mem")
            fi
            dry_flag=()
            $dry && dry_flag=(--dry)
            time_flag=()
            [[ -n "$walltime" ]] && time_flag=(--time "$walltime")
            submit_job "${gpu_flags[@]}" --queue "$queue" --mem "$submit_memory" \
                --cpus "$ncpu" --name "$batch_job_name" \
                "${time_flag[@]}" "${dry_flag[@]}" -- "$runner"
        fi
        echo
    done

    if (( local_failed )); then
        exit 1
    fi
    echo "Done."
    exit 0
fi

single_runner_root=""
for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx="${line%% *}"
    cfg_rel="${line#* }"
    config_path="$CANDEL_ROOT/$cfg_rel"
    posterior="${task_outputs[$i]}"

    echo "[INFO] === Task $idx ==="
    echo "[INFO] Config: $config_path"
    if [[ ! -f "$config_path" ]]; then
        echo "[WARNING] Config file not found: $config_path"; continue
    fi

    if $local_mode; then
        echo "[INFO] Running locally..."
        "$CANDEL_PYTHON" -u "$run_main" --config "$config_path" \
            --host-devices "$host_devices"
        _run_trgb_ppc "$idx" "$config_path" "$posterior"
    else
        gpu_flags=()
        if $is_gpu; then
            gpu_flags+=(--gpu)
            [[ -n "$gputype" ]] && gpu_flags+=(--gputype "$gputype")
            [[ -n "$gpu_mem" ]] && gpu_flags+=(--gpu-mem "$gpu_mem")
        fi
        dry_flag=()
        $dry && dry_flag=(--dry)
        time_flag=()
        [[ -n "$walltime" ]] && time_flag=(--time "$walltime")
        if $trgb_ppc; then
            if [[ -z "$single_runner_root" ]]; then
                stamp="$(date +%Y%m%d_%H%M%S)_$$"
                single_runner_root="$PWD/generated_batch_scripts/${task_index}/${stamp}"
            fi
            runner="$single_runner_root/task_${idx}${runner_ext}"
            _write_single_runner "$runner" "$idx" "$config_path" "$posterior"
            task_cmd=("$runner")
        else
            task_cmd=(/usr/bin/env "PYTHONPATH=${PYTHONPATH:-}" \
                "$CANDEL_PYTHON" -u "$run_main" --config "$config_path" \
                --host-devices "$host_devices")
        fi
        submit_job "${gpu_flags[@]}" --queue "$queue" --mem "$submit_memory" \
            --cpus "$ncpu" --name "task_${idx}" \
            "${time_flag[@]}" "${dry_flag[@]}" -- "${task_cmd[@]}"
    fi
    echo
done

echo "Done."
