#!/bin/bash -l
#
# Submit CANDEL inference tasks to the Glamdring queue system using addqueue.
# Equivalent of submit.sh (SLURM) but for Glamdring.
#
# Task files are generated by generate_tasks.py and have the format:
#   <index> <config_path>

set -e

# Extract a TOML key from a config file, with fallback to local_config.toml
get_toml_key() {
    local key="$1"
    local config="$2"
    local val
    val=$(grep -E "^${key} *= *" "$config" 2>/dev/null | sed -E "s/^${key} *= *\"([^\"]+)\"$/\1/")
    if [[ -z "$val" ]]; then
        local local_config
        local_config="$(cd "$(dirname "$0")/../.." && pwd)/local_config.toml"
        val=$(grep -E "^${key} *= *" "$local_config" 2>/dev/null | sed -E "s/^${key} *= *\"([^\"]+)\"$/\1/")
    fi
    echo "$val"
}

# ---- defaults ----
queue="gpulong"
ncpu=1
memory=16
gputype=""
local_mode=false

usage() {
    cat <<EOF
usage: $(basename "$0") [-h] [-q QUEUE] [-n NCPU] [-m MEMORY] [--gputype TYPE]
                        [--local] <task_index>

Submit CANDEL inference tasks to the Glamdring queue system.

positional arguments:
  task_index              Task file index (reads tasks_<index>.txt).
                          Suffix with 'X' to submit all split task files,
                          e.g. '0X' matches tasks_0X*.txt.

options:
  -h, --help              Show this help message and exit
  -q, --queue QUEUE       Glamdring queue name (default: $queue)
                          CPU queues: redwood, berg, cmb
                          GPU queues: gpulong, cmbgpu, optgpu
  -n, --ncpu NCPU         Number of CPUs (default: $ncpu)
  -m, --memory MEMORY     Memory per job in GB (default: $memory)
  --gputype TYPE          GPU type for GPU queues. If not set, a default is
                          chosen per queue:
                            gpulong  -> rtx2080with12gb
                            cmbgpu   -> rtx3090with24gb
                            optgpu   -> rtxa6000with48gb
                          Other options: rtx3070with8gb
                          optgpu: only one type (rtxa6000with48gb), --gputype not needed
  --local                 Run on login node instead of submitting
EOF
    exit 0
}

# ---- parse arguments ----
task_index=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)       usage ;;
        -q|--queue)      queue="$2"; shift 2 ;;
        -n|--ncpu)       ncpu="$2"; shift 2 ;;
        -m|--memory)     memory="$2"; shift 2 ;;
        --gputype)       gputype="$2"; shift 2 ;;
        --local)         local_mode=true; shift ;;
        *)               task_index="$1"; shift ;;
    esac
done

if [[ -z "$task_index" ]]; then
    echo "[ERROR] Missing task_index argument."
    echo "Usage: $(basename "$0") [-q QUEUE] [-n NCPU] [-m MEMORY] [--local] <task_index>"
    exit 1
fi

# Validate queue
valid_queues="redwood berg cmb gpulong cmbgpu optgpu"
if ! echo "$valid_queues" | grep -qw "$queue"; then
    echo "[ERROR] Invalid queue: $queue. Must be one of: $valid_queues"
    exit 1
fi

# Determine if GPU queue and set default gputype
is_gpu=false
case "$queue" in
    gpulong|cmbgpu|optgpu)
        is_gpu=true
        ;;  # don't set default --gputype; addqueue often rejects it
esac

if [[ -n "$gputype" ]] && ! $is_gpu; then
    echo "[ERROR] --gputype set but queue '$queue' is not a GPU queue."
    exit 1
fi

# Resolve task files: '0X' expands to tasks_0X*.txt, '0' reads tasks_0.txt
task_files=()
if [[ "$task_index" == *X ]]; then
    # Split mode: match all tasks_<base>X*.txt, sorted naturally
    while IFS= read -r f; do
        task_files+=("$f")
    done < <(compgen -G "tasks_${task_index}*.txt" | sort -V)

    if (( ${#task_files[@]} == 0 )); then
        echo "[ERROR] No split task files matching: tasks_${task_index}*.txt"
        exit 2
    fi
else
    # Single file mode
    task_files=("tasks_${task_index}.txt")
    if [[ ! -f "${task_files[0]}" ]]; then
        echo "[ERROR] Task file not found: ${task_files[0]}"
        exit 2
    fi
fi

# Read all task lines from all matched files
task_lines=()
task_line_sources=()
for tf in "${task_files[@]}"; do
    while IFS= read -r line || [[ -n "$line" ]]; do
        task_lines+=("$line")
        task_line_sources+=("$tf")
    done < "$tf"
done

frozen_root="/mnt/users/${USER}/frozen_candel"

echo "Glamdring task submission"
echo "============================================================"
if $local_mode; then
    echo "  Mode:        LOCAL (login node)"
else
    echo "  Mode:        SUBMIT (queue=$queue)"
fi
echo "  CPUs:        $ncpu"
echo "  Memory:      ${memory} GB"
if $is_gpu; then
    echo "  GPU type:    $gputype"
    echo "  Python:      python_exec_gpu (GPU venv)"
else
    echo "  Python:      python_exec (CPU venv)"
fi
if (( ${#task_files[@]} == 1 )); then
    echo "  Task file:   ${task_files[0]}"
else
    echo "  Task files:  ${#task_files[@]} files matching tasks_${task_index}.txt"
    for tf in "${task_files[@]}"; do
        echo "               - $tf"
    done
fi
echo "  Total tasks: ${#task_lines[@]}"
echo "  Frozen root: $frozen_root"
echo

echo "Tasks to run:"
for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx=$(echo "$line" | cut -d' ' -f1)
    config_path=$(echo "$line" | cut -d' ' -f2-)
    echo "  - [${task_line_sources[$i]}] Task $idx: $config_path"
done
echo

read -p "Proceed? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Aborting."
    exit 1
fi

if [[ ! -d "$frozen_root" ]]; then
    echo "[ERROR] Frozen package not found: $frozen_root"
    echo "Run freeze_candel.sh first."
    exit 4
fi

export PYTHONPATH="$frozen_root:$PYTHONPATH"

# --- Run each task ---
for i in "${!task_lines[@]}"; do
    line="${task_lines[$i]}"
    idx=$(echo "$line" | cut -d' ' -f1)
    config_path=$(echo "$line" | cut -d' ' -f2-)

    echo "[INFO] === Task $idx (${task_line_sources[$i]}) ==="
    echo "[INFO] Config: $config_path"

    if [[ ! -f "$config_path" ]]; then
        echo "[WARNING] Config file not found: $config_path"
        continue
    fi

    python_exec=""
    if $is_gpu; then
        python_exec=$(get_toml_key "python_exec_gpu" "$config_path")
        if [[ -n "$python_exec" ]]; then
            echo "[INFO] Using GPU python: $python_exec"
        else
            echo "[WARNING] python_exec_gpu not set, falling back to python_exec"
        fi
    fi
    if [[ -z "$python_exec" ]]; then
        python_exec=$(get_toml_key "python_exec" "$config_path")
    fi
    if [[ -z "$python_exec" ]]; then
        echo "[ERROR] Missing python_exec in: $config_path"
        continue
    fi

    pythoncmd="$python_exec $frozen_root/main.py --config $config_path --host-devices $ncpu"

    if $local_mode; then
        echo "[INFO] Running locally..."
        echo "  $pythoncmd"
        eval "$pythoncmd"
    else
        if $is_gpu; then
            if [[ -n "$gputype" ]]; then
                cm="addqueue -q $queue -s -m $memory --gpus 1 --gputype $gputype $pythoncmd"
            else
                cm="addqueue -q $queue -s -m $memory --gpus 1 $pythoncmd"
            fi
        else
            cm="addqueue -s -q $queue -n $ncpu -m $memory $pythoncmd"
        fi
        mkdir -p logs
        echo "[INFO] Submitting... (output -> logs/python-<jobid>.out)"
        echo "  $cm"
        (cd logs && eval "$cm")
    fi

    echo
    sleep 0.001
done

echo "Done."
